### PR TITLE
ZIO 2 version

### PR DESCRIPTION
**Pull request by vigoo**

### CODE REVIEW

**Comment by PhilAndrew** [comment]
How to build this branch in Scala 3? I get errors

**Comment by vigoo** [comment]
> How to build this branch in Scala 3? I get errors

What kind of errors? As you can see the CI builds the Scala 3 version as well: https://github.com/coralogix/zio-k8s/runs/7436082295?check_suite_focus=true

**Comment by PhilAndrew** [comment]
Think I've worked it out

sbt ++3.1.0 clean zio-k8s-client/compile zio-k8s-client/publishLocal

**Comment by vigoo** [comment]
Merging the ZIO 2 branch, current state of `master` captured onto a new `zio1` branch.

**Pull request merged**
