### PR TITLE
Upgrade to ZIO 2.0

### PR DESCRIPTION
**Pull request by sandeepkota**

### CODE REVIEW

**Comment by vigoo** [comment]
Hi @sandeepkota, I created a new branch called `zio2`. Could you retarget this PR to that and fix the small conflict please? I would like to merge your changes to that branch, set up snapshot publishing and iterate on the ZIO 2 version there.

**Comment by sandeepkota** [comment]
@vigoo Done ✅

**Comment by sandeepkota** [comment]
@vigoo migration of logging is still pending in this PR. I couldn't find proper documentation for migrating logging. Any help if appreciated. Thanks.

**Comment by vigoo** [comment]
No problem! Please run a `scalafmtAll` so it's green again and then I'll review and merge to the `zio2` branch, and collect the remaining steps that we can do as separate PRs.

**Comment by sandeepkota** [comment]
> No problem! Please run a `scalafmtAll` so it's green again and then I'll review and merge to the `zio2` branch, and collect the remaining steps that we can do as separate PRs.

Done!

**Comment by vigoo** [comment]
Interesting that it fails now as it was passing already once. Let me know if you have time to take a look, or want me to.

**Comment by vigoo** [comment]
Merged into `zio2` where we continue improving it

**Pull request merged**
