### PR TITLE
Upgrade to zio-config 4.0.0-RC16

### PR DESCRIPTION
**Pull request by gavares**
A few questions:
- Should this be a minor / major version bump since it's not backward compatible?
- I made some assumptions about required vs default values in the config for fields like `debug` and `disableHostnameVerification` and I'm not sure that what I have there is correct.

### CODE REVIEW

**Review by vigoo — DISMISSED** [review]

**Comment by gavares** [comment]
@vigoo - I added some questions in the description after you approved. Just want to make sure you saw them.

**Comment by vigoo** [comment]
I think this should be a major version bump

**Comment by ghostdogpr** [comment]
It looks like the docs are not updated on the microsite: https://coralogix.github.io/zio-k8s/docs/overview/overview_gettingstarted#configuring-with-zio-config--typesafe-config

**Comment by vigoo** [comment]
This should fix it: https://github.com/coralogix/zio-k8s/pull/554

**Pull request merged**
